data: datasets/7_classes_BC_xyr_converted/7_class_bccd_circle.yaml
img_size: 640
batch_size: 128
workers: 32
model_size: n
num_classes: 7
compile: false
tf32: true
optimizer: adamw
lr: 0.0005
weight_decay: 0.0001
momentum: 0.937
epochs: 250
amp: true
sched: cos
step_size: 50
gamma: 0.1
no_aug: false
l1: 1.0
legacy_cx: 0
legacy_cy: 1
legacy_r: 2
legacy_obj: 3
legacy_cls: 4
img_size_hint: 640
conf_thres: 0.25
iou_thres: 0.5
max_det: 300
eval_interval: 1
val_batches: 1
max_boxes_per_image: 100
save_model: best.pth
save_ckpt: ckpt.pth
csv_log: train_log.csv
early_stop_ap: 0.95
seed: 42
device: cuda:0
train_session_name: exp
